project_id = "qqhvdpzidjqcqwikpdeu"

[functions.football-api]
verify_jwt = false

[functions.ml-prediction]
verify_jwt = false

[functions.auto-verify]
verify_jwt = false

[functions.sync-live-matches]
verify_jwt = false

[functions.sync-matches]
verify_jwt = false

[functions.sync-standings]
verify_jwt = false

[functions.admin-cron-status]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.verify-purchase]
verify_jwt = false

[functions.play-store-webhook]
verify_jwt = false

[functions.sync-match-history]
verify_jwt = false
